### ISSUE TITLE
Android Support Lib 23.2.0

### ISSUE THREAD

**Issue by wscheffer** [viethoa/recyclerview-alphabet-fast-scroller-android#1]
With the new support lib Recycle Views now supports WRAP_CONTENT, this sees to causes in issues in onTouchEvent MotionEvent.ACTION_MOVE setRecyclerViewPosition(y)

**Comment by viethoa** [comment]
I fixed, thank you for your reminder. please let me know if have any issues again! very thank :)

**Comment by wscheffer** [comment]
Tested and works fine again. Thanks
