### ISSUE TITLE
Bubble

### ISSUE THREAD

**Issue by Kaway** [viethoa/recyclerview-alphabet-fast-scroller-android#2]
Does the bubble works out of the box ?

**Comment by viethoa** [comment]
I don't get your point? Can you please explain more what you want to do or what's problem are you stuck in?

**Comment by Kaway** [comment]
I want to know if there is something special to do to display the bubble, or if it works without any other configuration (the scroller perfectly works and I implemented getTextToShowInBubble

```
    @Override
    public String getTextToShowInBubble(int pos) {
        return "A";
    }
```

but the bubble doesn't show up

( can you label this issue as a question please ? )

**Comment by viethoa** [comment]
This function was mapped your RecycleView with fastScroller when you scrolling your RecycleView up or down, the fast-scroller will be select the bubble mapping with current selected item on your RecycleView. So you should set up on the right way to make it work, don't just return "A".
